version: "3.4"
services:
 vite_docker:
   image: node:20-alpine
   container_name: technical_test
   entrypoint: /bin/sh
   ports:
     - "3000:3000"
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true